routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// check admin
Route::get('/admin','CheckController@index')->name('admin.index');
Route::post('/admin/checkout','CheckController@checkout')->name('admin.checkout');
//dang ky
Route::get('/admin-register','CheckController@AdminRegister')->name('admin.register');
Route::post('/register/add-register/','CheckController@PostRegister')->name('register.post');
//check user

//login
Route::get('/login','FrontEndController@login')->name('login.index');
Route::post('/login/checkout','FrontEndController@postlogin')->name('login.checkout');
//sigup
Route::get('/sigup','FrontEndController@register')->name('sigup');
Route::post('/signup/add-signup/','FrontEndController@postSignup')->name('signup.post');

//Route::group(['middleware'=>'LoginUser'],function (){
//
//});


Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>'check'], function(){

    Route::resource('/user','UserController');
    Route::resource('/banner','BannerController');
    Route::resource('/category','CategoryController');
    Route::resource('/subcategory','SubCategoryController');
    Route::resource('/post','PostController');
    Route::resource('/product','ProductController');
    Route::resource('/setting','SettingController');
    Route::resource('/video','VideoController');
    Route::resource('/booking','ContactController');
    Route::resource('/photo','GalleryController');



});


//Frontennd
Route::get('/','FrontEndController@Trangchu')->name('trangchu');
Route::get('KOL','FrontEndController@KOL')->name('KOL');
Route::get('news','FrontEndController@tintuc')->name('tintuc');
Route::get('chi-tiet-tin-tuc/{slug}','FrontEndController@chitiettintuc')->name('chitiettintuc');
Route::get('booking','FrontEndController@booking')->name('booking');
//Route::get('','FrontEndController@lienhe')->name('lienhe');

Route::post('lien-he','FrontEndController@post_booking')->name('post');
Route::get('product','FrontEndController@store')->name('product');
Route::get('chi-tiet-san-pham/{slug}','FrontEndController@chitietsanpham')->name('chitietsanpham');


Route::get('login','FrontEndController@login')->name('login');
Route::get('signup','FrontEndController@signup')->name('signup');

Route::get('picture','FrontEndController@picture')->name('picture');
Route::get('video','FrontEndController@video')->name('video');
Route::get('setting','FrontEndController@setting')->name('setting');
//cart
Route::get('cart','CartController@giohang_index')->name('cart.index');
Route::get('add-to-cart/{id}','CartController@AddToCart')->name('add_cart');
Route::patch('update-cart','CartController@UpdateCart')->name('update_cart');
Route::delete('remove-cart','CartController@RemoveCart')->name('remove-cart');

//ajax location
Route::post('district/','LocationController@loadDistrict')->name('location.district');
Route::post('ward/','LocationController@loadWard')->name('location.ward');

//đặt hàng
//Route::get('order','CartController@Order')->name('order');
Route::get('/checkout', 'CartController@getCheckOut')->name('order');
Route::post('/checkout', 'CartController@postCheckOut')->name('post_checkout');










Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Banner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Banner extends Model
{
    public $timestamps = false;
    protected $table="banners";

    protected $fillable = ['name','image','description','is_active','created_at','updated_at'];
}

app/Http/Controllers/BannerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Banner;

class BannerController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Banner::all();
        $data = Banner::latest()->paginate(5);
        return view('BE.banner.index',[
            'data'=>$data,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('BE.banner.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request-> validate([
            'name'=>'required|max:255|unique:banners',

        ],[
                'name.required'=>'Bạn cần nhập tên banner',

        ]);

        $name = $request->input('name');
        $path_avatar = '';
        if ($request->hasFile('image')) {
            $file = $request->file('image');
            $fileExtension = $request->file('image')->getClientOriginalExtension(); // Lấy . của file
            $filename = '-'.time().'.'.$fileExtension;
            $path_upload = 'uploads/banner/';
            $file->move($path_upload, $filename);
            $path_avatar = $path_upload.$filename;
        }

        $is_active = $request->input('is_active');
        $description = $request->input('description');


        $banner = new Banner();
        $banner->name = $name;
        $banner->image = $path_avatar;
        $banner->description= $description;
        $banner->is_active=$is_active;
        $banner->save();
        session()->flash('success','Tạo thành công.');

        return redirect()->route('admin.banner.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = Banner::find($id);
        return view('BE.banner.edit',[
           'edit'=>$edit
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $name = $request->input('name');
        $is_active = $request->input('is_active');
        $description = $request->input('description');
        $path_avatar = '';
        $banner = Banner::find($id);
        if ($request->hasFile('image')) {
            $file = $request->file('image');
            $fileExtension = $request->file('image')->getClientOriginalExtension(); // Lấy . của file
            $filename = '-'.time().'.'.$fileExtension;
            $path_upload = 'uploads/banner/';
            $file->move($path_upload, $filename);
            $path_avatar = $path_upload.$filename;
            $banner->image = $path_avatar;

        }
        $banner->name = $name;
        $banner->description= $description;
        $banner->is_active=$is_active;
        $banner->save();
        session()->flash('success','Cập nhập thành công.');

        return redirect()->route('admin.banner.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete = Banner::destroy($id);
        if($delete){
            return response()->json(['success'=> 1 ,'message'=>'Thành Công']);
        } else{
            return response()->json(['success'=>0,'message'=>'Thất bại']);
        }
    }
}

resources/views/BE/banner/create.blade.php
@extends('BE.layout.main')
@section('content')
    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Thêm banner <a href="{{route('admin.banner.index')}}" class="btn bg-purple "><i class="fa fa-plus"></i> Danh sách banner</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#"> Banner </a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">

                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Thêm banner</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->

                        <form action="{{route('admin.banner.store')}}" method ="post" enctype="multipart/form-data">
                            @csrf
                            <div class="box-body">
                                <div class="col-md-6">

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Tên</label>
                                        <input type="text" class="form-control" name="name" placeholder="Enter name">
                                        @if($errors->has('name'))
                                            <label class="Text-red  " style="font-size:15px;font-weight:600;margin-top:5px;color:red" >
                                                <i class="fa fa-info"></i>{{$errors->first('name')}}
                                            </label>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputFile">Hình ảnh</label>
                                        <input type="file" id="image" name="image" >

                                        <p class="help-block">Example block-level help text here.</p>
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputPassword1"> Mô tả</label>
                                        <input type="text" class="form-control" name ="description" id="description" placeholder="Enter description">
                                        @if($errors->has('description'))
                                            <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px;color:red" >
                                                <i class="fa fa-info"></i>{{$errors->first('description')}}
                                            </label>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Trạng thái</label>
                                        <select class="form-control" name="is_active">
                                            <option value="">--Chọn--</option>
                                            <option value="1">Hiển thị</option>
                                            <option value="0">Không hiển thị</option>
                                        </select>

                                    </div>


                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="remember_token"> Check me out
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Tạo</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>

        </section>
        <!-- /.content -->
    </div>

@endsection

resources/views/BE/banner/edit.blade.php
@extends('BE.layout.main')
@section('content')
    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Thêm banner <a href="{{route('admin.banner.index')}}" class="btn bg-purple "><i class="fa fa-plus"></i> Danh sách banner</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#"> Banner </a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">

                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Chỉnh sửa banner</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->

                        <form action="{{route('admin.banner.update',['edit'=>$edit->id])}}" method ="post" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="box-body">
                                <div class="col-md-6">

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Nhập tên mới</label>
                                        <input value="{{$edit->name}}" type="text" class="form-control" name="name" placeholder="Enter name">
                                        @if($errors->has('name'))
                                            <label class="Text-red  " style="font-size:15px;font-weight:600;margin-top:5px;color:red" >
                                                <i class="fa fa-info"></i>{{$errors->first('name')}}
                                            </label>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputFile">Hình ảnh mới</label>
                                        <input type="file" id="image" name="image" >
                                        <img src="{{asset($edit->image)}} " width="100px" height="70px">
                                        <p class="help-block">Example block-level help text here.</p>
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputPassword1"> Mô tả</label>
                                        <input value="{{$edit->description}}" type="text" class="form-control" name ="description" id="description" placeholder="Enter description">
                                        @if($errors->has('description'))
                                            <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px;color:red" >
                                                <i class="fa fa-info"></i>{{$errors->first('description')}}
                                            </label>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Trạng thái</label>
                                        <select class="form-control" name="is_active">
                                            <option value="{{$edit->is_active}}">{{($edit->is_active == 1) ? 'Hiển thị' : 'không hiển thị' }}</option>
                                            <option value="1">Hiển thị</option>
                                            <option value="0">Không hiển thị</option>
                                        </select>

                                    </div>


                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="remember_token"> Lưu
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Cập nhập</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
            </div>

        </section>
        <!-- /.content -->
    </div>

@endsection

resources/views/BE/banner/index.blade.php
@extends('BE.layout.main')
@section('content')
    <div class="content-wrapper">
    <section class="content-header">
        <h1>
            DANH SÁCH BANNER <a href="{{route('admin.banner.create')}}" class="btn bg-purple btn-flat"><i class="fa fa-plus"></i> Thêm</a>

        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-user"></i> QUẢN LÝ BANNER </a></li>
        </ol>
    </section>
    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Danh Sách BANNER</h3>
                    </div>
                    @if(session()->has('success'))
                        <div class="alert alert-success">{{session()->get('success')}}</div>
                    @endif


                    <div class="box-body">
                        <table class="table table-border">
                            <tbody>
                            <tr>
                                <th style="width: 10px">STT</th>
                                <th>Tên </th>
                                <th>Hình ảnh</th>
                                <th>Mô tả</th>
                                <th>Trạng thái</th>

                                <th>Ngày tạo</th>
                                <th>Chức năng</th>
                            </tr>
                            @foreach($data as $key => $item)
                                <tr class="item-{{ $item->id }}">
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $item->name }}</td>
                                    <td><img src="{{asset($item->image)}}" width="70" height="100%"></td>
                                    <td>{{ $item->description }}</td>
                                    <td>{{ ($item->is_active==1)?'hiển thị':'Không hiển thị' }}</td>
                                    <td>{{ $item->created_at }}</td>

                                    <td>

                                        <a  href="{{route('admin.banner.edit',['id'=>$item->id])}}" class="btn btn-warning btn-edit"><i class="fa fa-pencil">Sửa</i></a>
                                        <a  href="" class="btn btn-warning btn-show"><i class="">Chi tiết</i></a>
                                        <button data-id="{{$item->id}}" class="btn btn-danger btn-delete"><i class="fa fa-trash"></i></button>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>

        </div>


    </section>

@endsection
        @section('my_js')

            <script type="text/javascript">
                $(document).ready(function () {
                    // Thiết lập csrf => chổng giả mạo
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    })

                    $('.btn-delete').on('click', function () {

                        let id = $(this).data('id');

                        // let result = confirm("Bạn có chắc chắn muốn xóa ?");

                        Swal.fire({
                            title: 'Bạn có chắc không?',
                            text: "Bạn có chắc chắn muốn xóa ?",
                            icon: 'warning',
                            showCancelButton: true,
                            confirmButtonColor: '#3085d6',
                            cancelButtonColor: '#d33',
                            confirmButtonText: 'Yes'
                        }).then((result) => {
                                if (result.isConfirmed) {
                                    $.ajax({
                                        url: 'admin/banner/' + id,
                                        type: 'DELETE',
                                        data: {
                                            name: ''
                                        },
                                        dataType: "json",
                                        success: function (res) {
                                            if (res.success != 'undefined' && res.success == 1) {
                                                $('.item-' + id).remove();
                                                Swal.fire(
                                                    'Deleted!',
                                                    'Xoá thành công',
                                                    'success'
                                                )
                                            }
                                            window.location.reload();
                                        },
                                        error: function (e) {
                                            console.log(e);
                                        }
                                    })
                                }
                            }
                        );

                    });
                });
            </script>

@endsection