routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// check admin
Route::get('/admin','CheckController@index')->name('admin.index');
Route::post('/admin/checkout','CheckController@checkout')->name('admin.checkout');
//dang ky
Route::get('/admin-register','CheckController@AdminRegister')->name('admin.register');
Route::post('/register/add-register/','CheckController@PostRegister')->name('register.post');
//check user

//login
Route::get('/login','FrontEndController@login')->name('login.index');
Route::post('/login/checkout','FrontEndController@postlogin')->name('login.checkout');
//sigup
Route::get('/sigup','FrontEndController@register')->name('sigup');
Route::post('/signup/add-signup/','FrontEndController@postSignup')->name('signup.post');

//Route::group(['middleware'=>'LoginUser'],function (){
//
//});


Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>'check'], function(){

    Route::resource('/user','UserController');
    Route::resource('/banner','BannerController');
    Route::resource('/category','CategoryController');
    Route::resource('/subcategory','SubCategoryController');
    Route::resource('/post','PostController');
    Route::resource('/product','ProductController');
    Route::resource('/setting','SettingController');
    Route::resource('/video','VideoController');
    Route::resource('/booking','ContactController');
    Route::resource('/photo','GalleryController');



});


//Frontennd
Route::get('/','FrontEndController@Trangchu')->name('trangchu');
Route::get('KOL','FrontEndController@KOL')->name('KOL');
Route::get('news','FrontEndController@tintuc')->name('tintuc');
Route::get('chi-tiet-tin-tuc/{slug}','FrontEndController@chitiettintuc')->name('chitiettintuc');
Route::get('booking','FrontEndController@booking')->name('booking');
//Route::get('','FrontEndController@lienhe')->name('lienhe');

Route::post('lien-he','FrontEndController@post_booking')->name('post');
Route::get('product','FrontEndController@store')->name('product');
Route::get('chi-tiet-san-pham/{slug}','FrontEndController@chitietsanpham')->name('chitietsanpham');


Route::get('login','FrontEndController@login')->name('login');
Route::get('signup','FrontEndController@signup')->name('signup');

Route::get('picture','FrontEndController@picture')->name('picture');
Route::get('video','FrontEndController@video')->name('video');
Route::get('setting','FrontEndController@setting')->name('setting');
//cart
Route::get('cart','CartController@giohang_index')->name('cart.index');
Route::get('add-to-cart/{id}','CartController@AddToCart')->name('add_cart');
Route::patch('update-cart','CartController@UpdateCart')->name('update_cart');
Route::delete('remove-cart','CartController@RemoveCart')->name('remove-cart');

//ajax location
Route::post('district/','LocationController@loadDistrict')->name('location.district');
Route::post('ward/','LocationController@loadWard')->name('location.ward');

//đặt hàng
//Route::get('order','CartController@Order')->name('order');
Route::get('/checkout', 'CartController@getCheckOut')->name('order');
Route::post('/checkout', 'CartController@postCheckOut')->name('post_checkout');










Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/BE/layout/footer.blade.php
{{--<footer class="main-footer">--}}
{{--    <div class="pull-right hidden-xs">--}}
{{--      <b>Version</b> 2.4.18--}}
{{--    </div>--}}
{{--    <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE</a>.</strong> All rights--}}
{{--    reserved.--}}
{{--  </footer>--}}

resources/views/BE/layout/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>  PV-ENTTAIMENT</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">

          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{{asset(Auth::User()->image)}}" class="user-image" alt="User Image">
              <span class="hidden-xs">{{Auth::User()->name}}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="{{asset(Auth::User()->image)}}" class="img-circle" alt="User Image">

                <p>

                  <small>Ngày Tạo:{{Auth::User()->created_at}}</small>
                </p>
              </li>
              <!-- Menu Body -->
{{--              <li class="user-body">--}}
{{--                <div class="row">--}}
{{--                  <div class="col-xs-4 text-center">--}}
{{--                    <a href="#">Followers</a>--}}
{{--                  </div>--}}
{{--                  <div class="col-xs-4 text-center">--}}
{{--                    <a href="#">Sales</a>--}}
{{--                  </div>--}}
{{--                  <div class="col-xs-4 text-center">--}}
{{--                    <a href="#">Friends</a>--}}
{{--                  </div>--}}
{{--                </div>--}}
{{--                <!-- /.row -->--}}
{{--              </li>--}}
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Trang cá nhân</a>
                </div>
                <div class="pull-right">
                  <a href="#" class="btn btn-default btn-flat">Đăng xuất</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

resources/views/BE/layout/main.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Dashboard</title>

    <meta name="csrf-token" content="{{csrf_token()}}">

    <base href="{{asset('')}}">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="backend/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="backend/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="backend/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="backend/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="backend/dist/css/skins/_all-skins.min.css">
    <!-- Morris chart -->

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
{{--@include('BE.layout.alert')--}}

@include('BE.layout.header')


@include('BE.layout.sidebar')


@yield('content')

@include('BE.layout.footer')



<!-- jQuery 3 -->
    <script src="backend/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="backend/bower_components/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
    <script src="backend/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Morris.js charts -->
    <script src="backend/bower_components/raphael/raphael.min.js"></script>
    <script src="backend/bower_components/morris.js/morris.min.js"></script>
    <!-- Sparkline -->
    <script src="backend/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>

    <!-- Slimscroll -->
    <script src="backend/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="backend/bower_components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="backend/dist/js/adminlte.min.js"></script>

    <script src="backend/dist/js/demo.js"></script>

    {{--<script src="js/jquery.form-validator.min.js"></script>--}}
    <script type="text/javascript">

        // $.validate({
        //
        // });
    </script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@yield('my_js')
@yield('scripts')

</body>
</html>

resources/views/BE/layout/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{asset(Auth::User()->image)}}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{Auth::User()->name}}</p>
          <a href="{{Auth::User()->is_active}}"><i class="fa fa-circle text-success"></i> {{(Auth::User()->is_active==0) ? 'online' : 'offline'}}</a>
        </div>
      </div>

      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="active">
          <a href="{{route('admin.user.index')}}">
            <i class="fa fa-user"></i> <span >QUẢN LÝ TÀI KHOẢN</span>
          </a>
        </li>
          <li class="active">
              <a href="{{route('admin.banner.index')}}">
                  <i class="fa fa-user"></i> <span >QUẢN LÝ BANNER</span>
              </a>
          </li>
          <li class="active">
              <a href="{{route('admin.subcategory.index')}}">
                  <i class="fa fa-user"></i> <span >QUẢN LÝ DANH MỤC</span>
              </a>
          </li>
          <li class="active">
              <a href="{{route('admin.product.index')}}">
                  <i class="fa fa-user"></i> <span >QUẢN LÝ SẢN PHẨM</span>
              </a>
          </li>
          <li class="active">
              <a href="{{route('admin.post.index')}}">
                  <i class="fa fa-user"></i> <span >QUẢN LÝ BÀI VIẾT</span>
              </a>
          </li>
          <li class="active">
              <a href="{{route('admin.setting.index')}}">
                  <i class="fa fa-user"></i> <span >PROFILE</span>
              </a>
          </li>
          <li class="active">
              <a href="{{route('admin.video.index')}}">
                  <i class="fa fa-user"></i> <span >QUẢN LÝ VIDEO</span>
              </a>
          </li>
          <li class="active">
              <a href="{{route('admin.booking.index')}}">
                  <i class="fa fa-user"></i> <span >BOOKING</span>
              </a>
          </li>
          <li class="active">
              <a href="{{route('admin.photo.index')}}">
                  <i class=""></i> <span >QUẢN LÝ GALLERY</span>
              </a>
          </li>
          <li class="active">
              <a href="">
                  <i class=""></i> <span >QUẢN LÝ ĐƠN HÀNG</span>
              </a>
          </li>


      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>