routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// check admin
Route::get('/admin','CheckController@index')->name('admin.index');
Route::post('/admin/checkout','CheckController@checkout')->name('admin.checkout');
//dang ky
Route::get('/admin-register','CheckController@AdminRegister')->name('admin.register');
Route::post('/register/add-register/','CheckController@PostRegister')->name('register.post');
//check user

//login
Route::get('/login','FrontEndController@login')->name('login.index');
Route::post('/login/checkout','FrontEndController@postlogin')->name('login.checkout');
//sigup
Route::get('/sigup','FrontEndController@register')->name('sigup');
Route::post('/signup/add-signup/','FrontEndController@postSignup')->name('signup.post');

//Route::group(['middleware'=>'LoginUser'],function (){
//
//});


Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>'check'], function(){

    Route::resource('/user','UserController');
    Route::resource('/banner','BannerController');
    Route::resource('/category','CategoryController');
    Route::resource('/subcategory','SubCategoryController');
    Route::resource('/post','PostController');
    Route::resource('/product','ProductController');
    Route::resource('/setting','SettingController');
    Route::resource('/video','VideoController');
    Route::resource('/booking','ContactController');
    Route::resource('/photo','GalleryController');



});


//Frontennd
Route::get('/','FrontEndController@Trangchu')->name('trangchu');
Route::get('KOL','FrontEndController@KOL')->name('KOL');
Route::get('news','FrontEndController@tintuc')->name('tintuc');
Route::get('chi-tiet-tin-tuc/{slug}','FrontEndController@chitiettintuc')->name('chitiettintuc');
Route::get('booking','FrontEndController@booking')->name('booking');
//Route::get('','FrontEndController@lienhe')->name('lienhe');

Route::post('lien-he','FrontEndController@post_booking')->name('post');
Route::get('product','FrontEndController@store')->name('product');
Route::get('chi-tiet-san-pham/{slug}','FrontEndController@chitietsanpham')->name('chitietsanpham');


Route::get('login','FrontEndController@login')->name('login');
Route::get('signup','FrontEndController@signup')->name('signup');

Route::get('picture','FrontEndController@picture')->name('picture');
Route::get('video','FrontEndController@video')->name('video');
Route::get('setting','FrontEndController@setting')->name('setting');
//cart
Route::get('cart','CartController@giohang_index')->name('cart.index');
Route::get('add-to-cart/{id}','CartController@AddToCart')->name('add_cart');
Route::patch('update-cart','CartController@UpdateCart')->name('update_cart');
Route::delete('remove-cart','CartController@RemoveCart')->name('remove-cart');

//ajax location
Route::post('district/','LocationController@loadDistrict')->name('location.district');
Route::post('ward/','LocationController@loadWard')->name('location.ward');

//đặt hàng
//Route::get('order','CartController@Order')->name('order');
Route::get('/checkout', 'CartController@getCheckOut')->name('order');
Route::post('/checkout', 'CartController@postCheckOut')->name('post_checkout');










Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Subcategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subcategory extends Model
{
    public $timestamps = false;
    protected $fillable = ['name','is_active','created_at','updated_at'];

    public function product(){
        return $this->hasMany('App\Product');
    }
    public function post(){
        return $this->hasMany('App\Post');
    }
}

app/Http/Controllers/SubCategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Subcategory;

class SubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Subcategory::all();
        $data = Subcategory::latest()->paginate(5);
        return view('BE.subcategory.index',[
            'data'=>$data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('BE.subcategory.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required|max:255|unique:subcategories'

        ],[
            'name.required'=>'Bạn cần nhập tên',
            'name.unique'=>'Tên đã được dụng'
        ]);
        $name=$request->input('name');
        $is_active = $request->input('is_active');
        $sub = new Subcategory();
        $sub->name =  $name;
        $sub->is_active=$is_active ;
        $sub->save();
        session()->flash('success','Tạo thành công.');

        return redirect()->route('admin.subcategory.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = Subcategory::find($id);
        return view('BE.subcategory.edit',[
           'edit'=>$edit
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required|max:255|unique:subcategories'

        ],[
            'name.required'=>'Bạn cần nhập tên',
            'name.unique'=>'Tên đã được dụng'
        ]);
        $name=$request->input('name');
        $is_active = $request->input('is_active');
        $sub = Subcategory::find($id);
        $sub->name =  $name;
        $sub->is_active=$is_active ;
        $sub->save();
        session()->flash('success','Cập nhập thành công.');

        return redirect()->route('admin.subcategory.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete = Subcategory::destroy($id);
        if($delete){
            return response()->json(['success'=> 1 ,'message'=>'Thành Công']);
        } else{
            return response()->json(['success'=>0,'message'=>'Thất bại']);
        }
    }
}

resources/views/BE/subcategory/create.blade.php
@extends('BE.layout.main')
@section('content')

    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Thêm thông tin danh mục <a href="{{route('admin.subcategory.index')}}" class="btn bg-purple "><i
                        class="fa fa-plus"></i> Danh sách danh mục</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> danh sách</a></li>
                <li><a href="#">thông tin danh mục</a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">

                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Nhập thông tin danh mục</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->

                        <form role="form" action="{{route('admin.subcategory.store')}}" method="post"
                              enctype="multipart/form-data">
                            @csrf
                            <div class="box-body">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Tên danh mục </label>
                                        <input type="text" class="form-control" name="name" id="name"
                                               placeholder="nhập tiêu đề">
                                        @if($errors->has('name'))
                                            <label class="Text-red"
                                                   style="font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('name')}}
                                            </label>
                                        @endif
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1"> Trạng thái </label>
                                        <select class="form-control" name="is_active">
                                            <option value="">--Chọn--</option>
                                            <option value="1">Hiển thị</option>
                                            <option value="0">No</option>
                                        </select>
                                        @if($errors->has('is_active'))
                                            <label class="Text-red"
                                                   style=" font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('is_active')}}
                                            </label>
                                        @endif
                                    </div>

                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" id="remember"> Check me out
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Tạo</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>

        </section>


    </div>
@endsection
{{--@section('my_js')--}}
{{--    --}}{{--    <script src="backend/ckeditor/ckeditor.js"></script>--}}
{{--    <script src="//cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>--}}

{{--    <script type="text/javascript">--}}
{{--        $(function () {--}}
{{--            CKEDITOR.replace('ckeditor');--}}
{{--            CKEDITOR.config.pasteFormWordPromptCleanup = true;--}}
{{--            CKEDITOR.config.pasteFormWordRemoveFontStyles = false;--}}
{{--            CKEDITOR.config.pasteFormWordRemoveStyles = false;--}}
{{--            CKEDITOR.config.language = 'vi';--}}
{{--            CKEDITOR.config.htmlEncodeOutput = false;--}}
{{--            CKEDITOR.config.ProcessHTMLEntities = false;--}}
{{--            CKEDITOR.config.entities = false;--}}
{{--            CKEDITOR.config.entities_latin = false;--}}
{{--            CKEDITOR.config.ForceSimpleAmpersand = true;--}}
{{--            CKEDITOR.replace('short_description',{--}}
{{--                filebrowserBrowseUrl: 'backend/ckfinder/ckfinder.html',--}}
{{--                filebrowserUploadUrl: 'backend/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',--}}
{{--                filebrowserWindowWidth: '1000',--}}
{{--                filebrowserWindowHeight: '700'--}}
{{--            });--}}
{{--            CKEDITOR.replace('content',{--}}
{{--                filebrowserBrowseUrl: 'backend/ckfinder/ckfinder.html',--}}
{{--                filebrowserUploadUrl: 'backend/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',--}}
{{--                filebrowserWindowWidth: '1000',--}}
{{--                filebrowserWindowHeight: '700'--}}
{{--            });--}}

{{--        });--}}
{{--    </script>--}}
{{--@endsection--}}

resources/views/BE/subcategory/edit.blade.php
@extends('BE.layout.main')
@section('content')

    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Chỉnh sửa danh mục <a href="{{route('admin.subcategory.index')}}" class="btn bg-purple "><i
                        class="fa fa-plus"></i> Danh sách danh mục</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> danh sách</a></li>
                <li><a href="#">Chỉnh sửa danh mục</a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">

                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Nhập thông tin danh mục mới</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->

                        <form role="form" action="{{route('admin.subcategory.update',['edit'=>$edit->id])}}" method="post"
                              enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="box-body">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Tên danh mục mới</label>
                                        <input value="{{$edit->name}}" type="text" class="form-control" name="name" id="name"
                                               placeholder="nhập tiêu đề">
                                        @if($errors->has('name'))
                                            <label class="Text-red"
                                                   style="font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('name')}}
                                            </label>
                                        @endif
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1"> Trạng thái </label>
                                        <select class="form-control" name="is_active">
                                            <option value="">{{ ($edit->is_active==1)?'hiển thị':'Không hiển thị' }}</option>
                                            <option value="1">Hiển thị</option>
                                            <option value="0">No</option>
                                        </select>
                                        @if($errors->has('is_active'))
                                            <label class="Text-red"
                                                   style=" font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('is_active')}}
                                            </label>
                                        @endif
                                    </div>

                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" id="remember"> Check me out
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Cập nhập</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>

        </section>


    </div>
@endsection

resources/views/BE/subcategory/index.blade.php
@extends('BE.layout.main')
@section('content')
    <div class="content-wrapper">

        <section class="content-header">
            <h1>
                DANH SÁCH DANH MỤC <a href="{{route('admin.subcategory.create')}}" class="btn bg-purple btn-flat"><i
                        class="fa fa-plus"></i> Thêm</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-user"></i> QUẢN LÝ DANH MỤC </a></li>
            </ol>
        </section>

        <section class="content">

            <div class="row">
                <div class="col-md-12">
                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">Danh Sách </h3>
                        </div>
                        @if(session()->has('success'))
                            <div class="alert alert-success">{{session()->get('success')}}</div>
                        @endif
                        <div class="box-body">
                            <table class="table table-border">
                                <tbody>
                                <tr>
                                    <th style="width: 10px">STT</th>
                                    <th>Tên</th>
                                    <th>Trạng thái</th>
                                    <th>Ngày tạo</th>
                                    <th>Hành Động</th>
                                </tr>
                                @foreach($data as $key => $sub)

                                    <tr class="item-{{$sub->id}}">
                                        <td>{{$key+1}}</td>
                                        <td>{{$sub->name}}</td>
                                        <td>{{ ($sub->is_active==1)?'hiển thị':'Không hiển thị' }}</td>
                                        <td>{{$sub->created_at}}</td>
                                        <td>
                                            <a href="{{route('admin.subcategory.edit',['edit'=>$sub->id])}}"
                                               class="btn btn-warning btn-edit"><i class="fa fa-pencil"></i></a>
                                            <button data-id="{{$sub->id}}" class="btn btn-danger btn-delete"><i
                                                    class="fa fa-trash"></i>
                                            </button>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>


        </section>
        @endsection
        @section('my_js')

            <script type="text/javascript">
                $(document).ready(function () {
                    // Thiết lập csrf => chổng giả mạo
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    })

                    $('.btn-delete').on('click', function () {

                        let id = $(this).data('id');

                        // let result = confirm("Bạn có chắc chắn muốn xóa ?");

                        Swal.fire({
                            title: 'Bạn có chắc không?',
                            text: "Bạn có chắc chắn muốn xóa ?",
                            icon: 'warning',
                            showCancelButton: true,
                            confirmButtonColor: '#3085d6',
                            cancelButtonColor: '#d33',
                            confirmButtonText: 'Yes'
                        }).then((result) => {
                                if (result.isConfirmed) {
                                    $.ajax({
                                        url: 'admin/subcategory/' + id,
                                        type: 'DELETE',
                                        data: {
                                            name: ''
                                        },
                                        dataType: "json",
                                        success: function (res) {
                                            if (res.success != 'undefined' && res.success == 1) {
                                                $('.item-' + id).remove();
                                                Swal.fire(
                                                    'Deleted!',
                                                    'Xoá thành công',
                                                    'success'
                                                )
                                            }
                                            window.location.reload();
                                        },
                                        error: function (e) {
                                            console.log(e);
                                        }
                                    })
                                }
                            }
                        );

                    });
                });
            </script>

@endsection