routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// check admin
Route::get('/admin','CheckController@index')->name('admin.index');
Route::post('/admin/checkout','CheckController@checkout')->name('admin.checkout');
//dang ky
Route::get('/admin-register','CheckController@AdminRegister')->name('admin.register');
Route::post('/register/add-register/','CheckController@PostRegister')->name('register.post');
//check user

//login
Route::get('/login','FrontEndController@login')->name('login.index');
Route::post('/login/checkout','FrontEndController@postlogin')->name('login.checkout');
//sigup
Route::get('/sigup','FrontEndController@register')->name('sigup');
Route::post('/signup/add-signup/','FrontEndController@postSignup')->name('signup.post');

//Route::group(['middleware'=>'LoginUser'],function (){
//
//});


Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>'check'], function(){

    Route::resource('/user','UserController');
    Route::resource('/banner','BannerController');
    Route::resource('/category','CategoryController');
    Route::resource('/subcategory','SubCategoryController');
    Route::resource('/post','PostController');
    Route::resource('/product','ProductController');
    Route::resource('/setting','SettingController');
    Route::resource('/video','VideoController');
    Route::resource('/booking','ContactController');
    Route::resource('/photo','GalleryController');



});


//Frontennd
Route::get('/','FrontEndController@Trangchu')->name('trangchu');
Route::get('KOL','FrontEndController@KOL')->name('KOL');
Route::get('news','FrontEndController@tintuc')->name('tintuc');
Route::get('chi-tiet-tin-tuc/{slug}','FrontEndController@chitiettintuc')->name('chitiettintuc');
Route::get('booking','FrontEndController@booking')->name('booking');
//Route::get('','FrontEndController@lienhe')->name('lienhe');

Route::post('lien-he','FrontEndController@post_booking')->name('post');
Route::get('product','FrontEndController@store')->name('product');
Route::get('chi-tiet-san-pham/{slug}','FrontEndController@chitietsanpham')->name('chitietsanpham');


Route::get('login','FrontEndController@login')->name('login');
Route::get('signup','FrontEndController@signup')->name('signup');

Route::get('picture','FrontEndController@picture')->name('picture');
Route::get('video','FrontEndController@video')->name('video');
Route::get('setting','FrontEndController@setting')->name('setting');
//cart
Route::get('cart','CartController@giohang_index')->name('cart.index');
Route::get('add-to-cart/{id}','CartController@AddToCart')->name('add_cart');
Route::patch('update-cart','CartController@UpdateCart')->name('update_cart');
Route::delete('remove-cart','CartController@RemoveCart')->name('remove-cart');

//ajax location
Route::post('district/','LocationController@loadDistrict')->name('location.district');
Route::post('ward/','LocationController@loadWard')->name('location.ward');

//đặt hàng
//Route::get('order','CartController@Order')->name('order');
Route::get('/checkout', 'CartController@getCheckOut')->name('order');
Route::post('/checkout', 'CartController@postCheckOut')->name('post_checkout');










Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;
use App\Photo;
use Illuminate\Http\Request;

class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Photo::all();
        $data = Photo::latest()->paginate(10);

        return view('BE.gallery.index',[
           'data'=>$data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('BE.gallery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required|max:255|unique:photos',
            'image'=>'required|mimes:jpg,png,gif,svg|max: 10000',
            'is_active'=>'required|not_in:0',

        ],[
            'name.required'=>'bạn cần nhập tiêu đề',
            'name.unique'=>'tiêu đề đã được sử dụng',
            'image.required'=>'bạn cần chọn hình ảnh ',
            'image.image'=>'file cần có dạng jpg,png,gif,svg',
        ]);
        $name = $request->input('name');
        $is_active = $request->input('is_active');
        $path_avatar = '';
        if ($request->hasFile('image')) {
            // get file
            $file = $request->file('image');
            // get ten
            $fileExtension = $request->file('image')->getClientOriginalExtension(); // Lấy . của file
            $filename = $name.'-'.time().'.'.$fileExtension;
            // duong dan upload
            $path_upload = 'uploads/gallery/';
            // upload file
            $file->move($path_upload, $filename);
            $path_avatar = $path_upload.$filename;
        }
        $gal = new Photo();
        $gal ->name = $name;
        $gal->is_active=$is_active;
        $gal->image=$path_avatar;

        $gal->save();
        session()->flash('success','Thêm thành công');
        return redirect()->route('admin.photo.index');
    }

    public function destroy($id)
    {
        $delete = Photo::destroy($id);
        if($delete){
            return response()->json(['success'=> 1 ,'message'=>'Thành Công']);
        } else{
            return response()->json(['success'=>0,'message'=>'Thất bại']);
        }
    }
}

resources/views/BE/gallery/create.blade.php
@extends('BE.layout.main')
@section('content')

    <div class="content-wrapper">

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Thêm Hình Ảnh <a href="{{route('admin.photo.index')}}" class="btn bg-purple "><i
                        class="fa fa-plus"></i> Danh sách hình ảnh</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="{{route('admin.photo.index')}}"><i class="fa fa-dashboard"></i> danh sách</a></li>
                <li><a href="{{route('admin.photo.index')}}">thông tin hình ảnh</a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">

                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Nhập thông tin hình ảnh</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
{{--                        {{dd($request->all())}}--}}
                        <form role="form" action="{{route('admin.photo.store')}}" method="post"
                              enctype="multipart/form-data">
                            @csrf

                            <div class="box-body">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Tên Hình Ảnh</label>
                                        <input type="text" class="form-control" name="name" id="name"
                                               placeholder="nhập tên ảnh">
                                        @if($errors->has('name'))
                                            <label class="Text-red"
                                                   style="font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('name')}}
                                            </label>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Hình ảnh</label>
                                        <input type="file" id="image" name="image">
                                        <p class="help-block">Example block-level help text here.</p>
                                        @if($errors->has('image'))
                                            <label class="Text-red"
                                                   style="font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('image')}}
                                            </label>
                                        @endif
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1"> Hoạt động </label>
                                        <select class="form-control" name="is_active">
                                            <option value="select">--Chọn--</option>
                                            <option value="1">Hiển thị</option>
                                            <option value="0">No</option>
                                        </select>
                                        @if($errors->has('is_active'))
                                            <label class="Text-red"
                                                   style=" font-size:15px;font-weight:600;margin-top:5px;color:red">
                                                <i class="fa fa-info"></i>{{$errors->first('is_active')}}
                                            </label>
                                        @endif
                                    </div>

                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" id="remember"> Check me out
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Thêm</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>

        </section>


    </div>
@endsection

resources/views/BE/gallery/index.blade.php
@extends('BE.layout.main')
@section('content')
    <div class="content-wrapper">

        <section class="content-header">
            <h1>
                Quản lý bộ sưu tập <a href="{{route('admin.photo.create')}}" class="btn bg-purple btn-flat"><i
                        class="fa fa-plus"></i> Thêm hình ảnh</a>

            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-user"></i> Quản lý bộ sưu tập</a></li>
            </ol>
        </section>

        <section class="content">

            <div class="row">
                <div class="col-md-12">
                    <div class="box">

                        <div class="box-header with-border">

                            <h3 class="box-title">Bộ sưu tập </h3>

                        </div>
                        @if(session()->has('success'))
                            <div class="alert alert-success">{{session()->get('success')}}</div>
                        @endif


                        <div class="box-body">
                            <table class="table table-border">
                                <tbody>
                                <tr>
                                    <th style="width: 10px">STT</th>
                                    <th>Tên Hình Ảnh</th>
                                    <th>Hình ảnh</th>
                                    <th>Trạng thái</th>
                                    <th>Ngày tạo</th>
                                    <th>Ngày cập nhập</th>
                                    <th>Hành Động</th>
                                </tr>
                                @foreach($data as $key=>$photo)
                                    <tr class="item-{{$photo->id}}">
                                        <td>{{$key+1}}</td>
                                        <td>{{$photo->name}}</td>
                                        <td><img src="{{asset($photo->image)}}" width="70" height="100%"></td>

                                        <td>{{($photo->is_active==1)?'Hiển thị':'Không hiển thị'}}</td>
                                        <td>{{$photo->created_at}}</td>
                                        <td>{{$photo->updated_at}}</td>
                                        <td>
                                            <a href="{{route('admin.product.edit',['edit'=>$photo->id])}}"
                                               class="btn btn-warning btn-edit"><i class="fa fa-pencil"></i></a>
                                            <button data-id="{{$photo->id}}" class="btn btn-danger btn-delete"><i
                                                    class="fa fa-trash"></i>
                                            </button>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="box-footer clearfix">
                            {{$data->links()}}
                        </div>
                    </div>
                </div>

            </div>


        </section>
        @endsection
        @section('my_js')

            <script type="text/javascript">
                $(document).ready(function () {
                    // Thiết lập csrf => chổng giả mạo
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    })

                    $('.btn-delete').on('click', function () {

                        let id = $(this).data('id');

                        // let result = confirm("Bạn có chắc chắn muốn xóa ?");

                        Swal.fire({
                            title: 'Bạn có chắc không?',
                            text: "Bạn có chắc chắn muốn xóa ?",
                            icon: 'warning',
                            showCancelButton: true,
                            confirmButtonColor: '#3085d6',
                            cancelButtonColor: '#d33',
                            confirmButtonText: 'Yes'
                        }).then((result) => {
                                if (result.isConfirmed) {
                                    $.ajax({
                                        url: 'admin/photo/' + id,
                                        type: 'DELETE',
                                        data: {
                                            name: ''
                                        },
                                        dataType: "json",
                                        success: function (res) {
                                            if (res.success != 'undefined' && res.success == 1) {
                                                $('.item-' + id).remove();
                                                Swal.fire(
                                                    'Deleted!',
                                                    'Xoá thành công',
                                                    'success'
                                                )
                                            }
                                            window.location.reload();
                                        },
                                        error: function (e) {
                                            console.log(e);
                                        }
                                    })
                                }
                            }
                        );

                    });
                });
            </script>

@endsection